### ISSUE TITLE
Vertical Images

### ISSUE THREAD

**Issue by phil-03** [s-richards/slideshow#1]
Hey S-Richards, there is nothing wrong with your code, I just can't figure out why the images are displayed all at once vertically on my homepage. its probably something minor that I'm just forgetting, any ideas?

**Comment by s-richards** [comment]
It's hard to say without seeing the code. If you post it here or have a link to it I'll take a look and see if I can figure out what the problem is.

**Comment by phil-03** [comment]
Thanks for responding Sam,

        I attached the main file (homepage) index.php and the rest of the
code is just your files.
        The link to the page is linus.highpoint.edu/~sga/part2 .

**Comment by s-richards** [comment]
It looks like there are a couple of problems.

1. The first issue is that the slidshow css and js files aren't loading due to a 403 error (see the screenshot below).
![screenshot of 403 errors](https://cloud.githubusercontent.com/assets/5415348/18298971/af5c16a6-7471-11e6-84e7-db1f2ca6f392.jpg)

2. Another issue is with the code in your html file:
```html
<div class="slideshow slideshow-three">
    <div class="slideshow-slide-list overlay">
        <figure class="slideshow-slide">
            <img src="../images/sga3.jpg" alt="image 1">
            <figcaption class="slideshow-caption">Slide 1 caption</figcaption>
        </figure>
        <figure class="slideshow-slide">
            <img src="../images/sga2.jpg" alt="image 2">
            <figcaption class="slideshow-caption">Slide 2 caption</figcaption>
        </figure>
    </div>
</div>
```
Then towards the end of the page you have this code:
```html
<script>
   var el = document.getElementById('slideshow-elements-id');
   Slideshow(el);
   /* var slideshowEl = document.querySelector('.slideshow');
    Slideshow(slideshowEl, {
        allowSwipe: true,
        showIndicators: true,
        transitionEffect: "slide",
    });*/
</script>

<script src="slideshow/dist/js/slideshow.min.js"></script>
```
First, I don't see an element in your html markup with the id of 'slideshow-elements-id'. It looks like the slideshow container element is `<div class="slideshow slideshow-three">`, as seen in the first block of code above. You could either add an id of 'slideshow-elements-id' to that element or you could change `var el = document.getElementById('slideshow-elements-id');` to `var el = document.querySelector('.slideshow.slideshow-three');`. Another issue with your code is that in the second large block of code above you call `Slideshow(el)'` before the `<script src="slideshow/dist/js/slideshow.min.js"></script>`. To fix both these issues just change the second block of code above to this:
```html
<script src="slideshow/dist/js/slideshow.min.js"></script>
<script>
   var el = document.querySelector('.slideshow');
   Slideshow(el);
   /* var slideshowEl = document.querySelector('.slideshow');
    Slideshow(slideshowEl, {
        allowSwipe: true,
        showIndicators: true,
        transitionEffect: "slide",
    });*/
</script>
```

If these two fixes don't work let me know and I'll take another look.

**Comment by phil-03** [comment]
Okay, so I fixed the errors above except for the the reference-error under
console. Any ideas why "Slideshow" would not be defined because its still
not loading correctly? I didn't change anything in my css files.
http://linus.highpoint.edu/~sga/part2/

**Comment by s-richards** [comment]
The reason 'Slideshow' isn't defined is because the browser is encountering a 403 (forbidden) error when it attempts to load `<script src="slideshow/dist/js/slideshow.min.js"></script>` (it's also getting a 403 error for the slideshow.min.css file).

It looks like you have css files and js files being loaded properly from the '/~sga/part2/' directory (http://linus.highpoint.edu/~sga/part2/styles.css, http://linus.highpoint.edu/~sga/part2/styleSheet.css, etc). Try putting the `slideshow.min.js` and `slideshow.min.css` files in that directory and change their respective tags to be:
```html
<link href="slideshow.min.css" rel="stylesheet">
```
```html
<script src="slideshow.min.js"></script>
```

**Comment by phil-03** [comment]
Thanks for all your help, I finally got it working after moving files
around. You saved me a ton of time! The rest is just css manipulation, so I
should have little to no problems.

**Comment by s-richards** [comment]
Glad you got it working!
